[package]
name = "photo-tool-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ftpt"
path = "src/main.rs"

[dependencies]
photo-domain = { path = "../photo-domain" }
photo-engine = { path = "../photo-engine" }
photo-config = { path = "../photo-config" }
photo-recognize = { path = "../photo-recognize" }

chrono.workspace = true
font-kit.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
image.workspace = true
zune-core.workspace = true
zune-jpeg.workspace = true
oneshot.workspace = true
parking_lot.workspace = true
rayon.workspace = true
rfd.workspace = true
rust-embed.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-log.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[build-dependencies]
embed-resource.workspace = true
image.workspace = true
