// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  弹出目录选择对话框，返回选中目录（取消返回 null）。
	 *  只选目录，扫描由前端随后调 scan_directory 触发。
	 */
	pickDirectory: () => __TAURI_INVOKE<string | null>("pick_directory"),
	/**
	 *  扫描目录：spawn_blocking 内 scanner 扫描 → folder_db 打开/三表同步 →
	 *  读 exif_cache 回填 → 返回总数；随后后台任务做 EXIF 增量提取 + 缩略图预生成。
	 */
	scanDirectory: (path: string) => __TAURI_INVOKE<number>("scan_directory", { path }),
	/**  全量下推当前扫描结果（前端筛选/排序在 TS 侧做，零 IPC） */
	getCaptures: () => __TAURI_INVOKE<CaptureMeta[]>("get_captures"),
	/**
	 *  设置评分（0 = 清除）。写 folder_db xmp_meta 真相表 + 更新内存副本；
	 *  失败返回 Err，前端重拉回滚（乐观更新回滚语义由前端承担）。
	 */
	setRating: (paths: string[], rating: number) => typedError<null, string>(__TAURI_INVOKE("set_rating", { paths, rating })),
	/**  设置 Pick/Reject 旗标（None = 清除，对应 GPUI 的 U 键） */
	setFlag: (paths: string[], flag: "Pick" | "Reject" | null) => typedError<null, string>(__TAURI_INVOKE("set_flag", { paths, flag })),
	/**  设置颜色标签（None = 清除） */
	setColorLabel: (paths: string[], label: "None" | "Red" | "Yellow" | "Green" | "Blue" | "Purple" | null) => typedError<null, string>(__TAURI_INVOKE("set_color_label", { paths, label })),
	/**
	 *  设置关键词标签（全量替换语义）：写 folder_db keywords 真相表 + 更新内存副本。
	 *  关键词归一化（去首尾空白/去空串/去重）与 set_rating 同语义：失败返回 Err，
	 *  前端重拉回滚（乐观更新回滚语义由前端承担）。空数组 = 清空全部关键词。
	 */
	setKeywords: (paths: string[], keywords: string[]) => typedError<null, string>(__TAURI_INVOKE("set_keywords", { paths, keywords })),
	/**  列出收藏目录（AppConfig.favorite_dirs） */
	listFavorites: () => __TAURI_INVOKE<string[]>("list_favorites"),
	/**  添加收藏目录（已存在则忽略；保存配置） */
	addFavorite: (path: string) => __TAURI_INVOKE<void>("add_favorite", { path }),
	/**  移除收藏目录并保存配置 */
	removeFavorite: (path: string) => __TAURI_INVOKE<void>("remove_favorite", { path }),
	/**  列出最近打开的目录（最新在前，最多 10 个；scan_impl 扫描时维护） */
	listRecent: () => __TAURI_INVOKE<string[]>("list_recent"),
	/**
	 *  列出 path 的一层子目录（侧栏目录树数据源；逐层展开逐层调本命令）。
	 *  photo_count 只统计每个子目录**直接**包含的照片数（单层语义，与扫描一致），
	 *  不做递归——目录树按需懒加载，避免一次遍历全树。
	 *  跳过 `.pt` 元数据目录（缩略图/中心库，非照片目录）。
	 */
	listSubdirs: (path: string) => typedError<SubdirInfo[], string>(__TAURI_INVOKE("list_subdirs", { path })),
	/**
	 *  名录库全量鸟种（拼音排序，筛选下拉数据源）。
	 *  名录库在 exe 同级 data/pica_ref.db（与 Recognizer 同路径约定）；
	 *  photo-recognize 的 list_all_species 已按 cn_name_pinyin 排序（缺失回退中文名）。
	 */
	listBirdSpecies: () => typedError<string[], string>(__TAURI_INVOKE("list_bird_species")),
	/**
	 *  计算直方图（预览尺寸解码，JPEG DCT 降采样 / RAW half_size 预览，不解 24MP 全尺寸）。
	 *  内存缓存按 (路径, 文件大小)（InfoPanel 切图回来复用；文件覆盖自动失效）；
	 *  失败返回文案（如 RAW 解码异常）。
	 */
	getHistogram: (path: string) => typedError<HistogramPayload, string>(__TAURI_INVOKE("get_histogram", { path })),
	/**
	 *  剪切叠加图（RGBA PNG 字节：红 = 高光溢出、蓝 = 死黑，其余透明；长边 ~800）。
	 *  加载不阻塞主图：前端异步拉取后以主图同尺寸叠放；内存缓存按 (路径, 文件大小)。
	 */
	getClippingMask: (path: string) => typedError<number[], string>(__TAURI_INVOKE("get_clipping_mask", { path })),
	/**
	 *  批量识别：spawn_blocking 后台逐张识别（多线程分块，每线程独占 Recognizer——
	 *  Session 需 &mut，不可跨线程共享，照 GPUI spawn_batch_recognize）。
	 *  逐张 emit recognize:progress；每张完成后写 folder_db recognition 表（rel 键与代际
	 *  无关，工作线程直接 upsert）+ 锁 AppState 更新内存 CaptureMeta（带代际校验）；
	 *  全部完成 emit recognize:done 并复位进行中标记。单张失败不中止整体（failed 计数）。
	 *  取消：cancel_recognition 置位令牌，各线程逐张检查后提前退出（取消也照常 emit done）。
	 */
	recognizeCaptures: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("recognize_captures", { paths })),
	/**  请求取消批量识别：置位取消令牌，识别循环逐张检查后提前退出 */
	cancelRecognition: () => __TAURI_INVOKE<void>("cancel_recognition"),
	/**
	 *  批量操作干跑：只计算操作集与目标路径，不碰文件。
	 *  操作集 = 当前扫描结果全量（Tauri 端筛选在 TS 侧，后端无筛选状态，前端在无筛选
	 *  条件时自行禁用）；formats 非空时按主文件格式过滤；sync_siblings 时按引擎
	 *  expand_with_siblings 把同名兄弟并入（formats 即兄弟格式白名单）。siblingCount = 扩展新增数。
	 */
	batchOpPreview: (op: BatchOpType, options: BatchOpOptions) => typedError<BatchOpPreview, string>(__TAURI_INVOKE("batch_op_preview", { op, options })),
	/**
	 *  批量操作执行：spawn_blocking 后台执行（engine::batch_ops::execute），逐文件 emit
	 *  batch:progress，完成 emit batch:done。语义照 GPUI run_batch_op：
	 *  1. 重扫源目录取完整 Capture（ops 层需要 source_files 全列表操作兄弟文件）
	 *  2. 操作集 = 全量；formats 非空按主文件格式过滤；sync_siblings 时 expand_with_siblings
	 *  3. Delete 走 ops::delete_capture（回收站）；Move/Delete 后的重扫由前端负责
	 *     （前端会重调 scan_directory，本命令不触发）
	 */
	batchOpExecute: (op: BatchOpType, options: BatchOpOptions) => typedError<BatchOpResult, string>(__TAURI_INVOKE("batch_op_execute", { op, options })),
	/**
	 *  撤销最近一次批量操作（移动/复制/模板重命名；删除走回收站不在范围）：
	 *  1. 取走内存日志（单槽：撤销后即空，再次 Ctrl+Z 报「没有可撤销的批量操作」）
	 *  2. 逐条执行逆操作（move 回移 / rename 改回 / copy 删副本），跳过/失败不中止后续
	 *  3. 成功撤销的 Move/Rename 逆向同步 xmp_meta/识别/调整行（复用 sync_move_xmp /
	 *     sync_rename_xmp 反向调用；正向批次未做 sidecar 同步时为空操作，幂等无害）
	 *  4. scan_impl 全量重扫（更新内存 captures + emit scan:done 驱动前端 reload）
	 */
	undoBatchOperation: () => typedError<UndoBatchResult, string>(__TAURI_INVOKE("undo_batch_operation")),
	/**  读取单张调整参数（ADR 0007；无记录返回全零 = 无调整） */
	getAdjustments: (path: string) => __TAURI_INVOKE<AdjustParams>("get_adjustments", { path }),
	/**
	 *  设置调整参数：持久化到 folder_db adjustments 表 + emit thumb:ready 触发预览刷新
	 *  （前端按事件失效缓存并以新 ?v= 重载 master 预览；ptimg handler 侧带调整参数时
	 *  经引擎渲染输出）。防御 DB 坏值：Q15 定点饱和要求 saturation∈[-100,100]，
	 *  钳制后再入内存（同 GPUI refresh_adjustments_sync）。
	 */
	setAdjustments: (path: string, params: AdjustParams) => typedError<null, string>(__TAURI_INVOKE("set_adjustments", { path, params })),
	/**  读取完整配置（前端启动时据此应用主题/字体等；AppConfig 已 derive specta） */
	getAppConfig: () => __TAURI_INVOKE<AppConfig>("get_app_config"),
	/**
	 *  读取单张完整识别结果（InfoPanel 识别 tab）。
	 *  按完整路径查 folder_db recognition 表（与 get_adjustments 同键约定：正斜杠 rel）；
	 *  无记录 / 未打开目录 / 路径越界一律返回 None（前端据此显示「未识别」）。
	 */
	getRecognition: (path: string) => typedError<{
	status: RecognitionStatus,
	/**  Top-1 鸟种匹配（mapping 失败 / 未检出时为 None） */
	bird: BirdMatch | null,
	/**  Top-1 原始类别号（诊断用） */
	classIndex: number | null,
	/**  Top-1 置信度（0–100） */
	confidence: number | null,
	/**  检测框（检测失败为 None） */
	bbox: BBox | null,
	/**  鸟眼锐度分（连续，仅保证单调性，阈值后置；无鸟/有鸟无眼/评分失败为 None） */
	eyeSharpness: number | null,
	/**  评分所用眼框（归一化坐标，相对全图；无锐度分为 None） */
	eyeBbox: BBox | null,
	/**  Top-5 候选（含 Top-1 自身除外的备选；分类失败为空） */
	candidates: BirdCandidate[],
	failureStage: RecognitionFailureStage,
	/**  ISO8601 时间戳 */
	recognizedAt: string,
} | null, string>(__TAURI_INVOKE("get_recognition", { path })),
	/**
	 *  手动修正鸟种（对齐 GPUI correct_bird_by_name）：名录库按中文名匹配 → 构造
	 *  Confirmed Recognition（人工指定即权威结论：置信度 100%，保留原检测框/眼锐度/
	 *  眼框数据）→ 写 recognition 表 → 同步内存 CaptureMeta（bird_name/confidence/
	 *  status）→ emit thumb:ready 供前端刷新网格识别 chip。
	 */
	correctBird: (path: string, birdName: string) => typedError<null, string>(__TAURI_INVOKE("correct_bird", { path, birdName })),
	/**
	 *  单张/多张删除（回收站，无确认——对齐 GPUI Delete 键语义）。
	 *  与 batch_op_execute 的 Delete 分支同编排：重扫源目录取完整 Capture（ops 层
	 *  delete_capture 需要 source_files 才能操作同名兄弟文件）→ 逐个删除 → 仅删除
	 *  成功者同步 sidecar 三表（识别/调整/评分色标旗标行，防孤儿行）→ 从内存
	 *  captures 移除并重索引 → scan_generation 换代（在途 EXIF/缩略图任务按代数
	 *  丢弃，防张冠李戴）→ emit scan:done {total, directory}，前端 store 据此自动
	 *  reload()。任一失败不中止整体（与批量语义一致）；全部失败才返回 Err。
	 */
	deleteCaptures: (paths: string[]) => typedError<null, string>(__TAURI_INVOKE("delete_captures", { paths })),
	/**
	 *  导出调整结果（全尺寸烘焙，ADR 0007）：engine adjustments 渲染 + convert 保存
	 *  JPEG。命名 `{stem}_adjusted.jpg`，已存在自动追加 `_1/_2` 序号（不覆盖原文件，
	 *  照 GPUI export_adjusted）。output_dir = None 时导出到源文件所在目录。RAW
	 *  全尺寸 16-bit 解码约 3-5s，spawn_blocking 异步执行。返回最终输出路径（前端
	 *  状态栏展示）。导出是一次性烘焙，不改动内存 CaptureMeta（无对应字段）。
	 */
	exportAdjusted: (path: string, outputDir: string | null) => typedError<string, string>(__TAURI_INVOKE("export_adjusted", { path, outputDir })),
	/**
	 *  系统字体枚举（设置面板字体下拉数据源）。
	 *  zed-font-kit（font-kit 的 zed fork，workspace 已 pin）：Windows 走 DirectWrite
	 *  系统字体集合（SystemSource::new() 无失败路径）；family 名排序后返回。
	 */
	listSystemFonts: () => typedError<string[], string>(__TAURI_INVOKE("list_system_fonts")),
	/**
	 *  更新并保存配置（设置面板）：钳制校验后替换 st.config + save_config。
	 *  钳制范围：leftPanelWidth 200–480、rightPanelWidth 200–480、
	 *  recognitionThreadCount 1–4、thumbnailSize 64–1024（网格 cell = 尺寸 + 56，
	 *  越界值钳到合理区间，与 GPUI 设置语义一致，非法输入不报错）。
	 */
	setAppConfig: (config: AppConfig) => typedError<null, string>(__TAURI_INVOKE("set_app_config", { config })),
	/**
	 *  全局鸟种统计（统计视图汇总条 + 左栏列表）：全库聚合、张数降序。
	 *  数据源 = 启动时打开的 exe 同级 data/global.db；打开失败（降级 None）返回空概览。
	 */
	getSpeciesStats: () => typedError<SpeciesOverview, string>(__TAURI_INVOKE("get_species_stats")),
	/**
	 *  某鸟种全部照片定位（统计视图右栏网格）：folder + rel_path，前端拼绝对路径后
	 *  经 ptimgUrl('thumb', 绝对路径) 渲染缩略图。
	 */
	getSpeciesPhotos: (birdName: string) => typedError<SpeciesPhoto[], string>(__TAURI_INVOKE("get_species_photos", { birdName })),
	/**
	 *  全局识别命中率（统计视图「识别命中率」区块）：按鸟种聚合 predicted /
	 *  corrected_away / accuracy（accuracy = 1 - corrected_away/predicted）。
	 *  数据源 = 启动时打开的 exe 同级 data/global.db；打开失败（降级 None）返回空。
	 */
	getCorrectionStats: () => typedError<CorrectionStat[], string>(__TAURI_INVOKE("get_correction_stats")),
	/**
	 *  高频鸟种（修正鸟种下拉「常用」分组）：species_index 按张数降序、去 NULL/空名。
	 *  本机使用频次即区域相关性代理（离线替代区域名录）。
	 */
	getFrequentSpecies: (limit: number) => typedError<string[], string>(__TAURI_INVOKE("get_frequent_species", { limit })),
	/**
	 *  检测可移动驱动器（Windows 原生 API：GetLogicalDrives + GetDriveTypeW +
	 *  GetVolumeInformationW；非 Windows 返回空）。SD 卡/U 盘即 DRIVE_REMOVABLE。
	 */
	listImportDrives: () => __TAURI_INVOKE<ImportDrive[]>("list_import_drives"),
	/**
	 *  递归扫描导入源（整棵子树，不限 DCIM）：EXIF 拍摄日期优先，回退 mtime。
	 *  返回候选列表（前端据此展示「N 张」并送入 plan_import 干跑）。
	 */
	scanImportSource: (path: string) => typedError<ImportCandidate[], string>(__TAURI_INVOKE("scan_import_source", { path })),
	/**
	 *  生成导入计划（干跑）：按日期分组建 destRoot/YYYY-MM-DD/ + 目标去重
	 *  （目标已存在同名同大小 = 已完成导入跳过；同名不同大小 = 防覆盖跳过）。
	 *  不碰任何文件；跳过清单供前端预览前 20 条。
	 */
	planImport: (candidates: ImportCandidate[], destRoot: string) => typedError<ImportPlan, string>(__TAURI_INVOKE("plan_import", { candidates, destRoot })),
	/**
	 *  执行导入：spawn_blocking 内逐文件委托 engine 复制/移动，逐文件 emit
	 *  import:progress，完成 emit import:done。返回 ImportResult（= done 负载）。
	 *  完成后若目标根目录处于当前打开目录之内 → 触发重扫（scan_impl），
	 *  新导入的照片立即出现在网格；否则不动当前目录。
	 */
	executeImport: (plan: ImportPlan, destRoot: string, mode: ImportMode) => typedError<ImportResult, string>(__TAURI_INVOKE("execute_import", { plan, destRoot, mode })),
	/**
	 *  批量重命名（模板模式，T1 批次）：对 `paths`（前端按筛选结果主路径传入，
	 *  顺序即序号顺序）应用命名模板。占位符数据从内存 CaptureMeta 取——鸟种
	 *  `bird_name`、拍摄日期 `date_taken`、相机型号 `camera_model`，序号从
	 *  `start_seq` 递增（补零 3 位，template.rs 渲染）。
	 * 
	 *  重扫源目录取完整 Capture（ops 层需要 source_files 全列表同步改名兄弟文件）；
	 *  成功后同步 folder_db 三表键（recognition/adjustments 相对路径、xmp_meta 完整
	 *  路径）。逐张 emit `batch:progress`，完成 emit `batch:done`（复用批量操作进度
	 *  通道，与 batch_op_execute 语义一致）。返回 `BatchOpResult` 形态汇总。
	 */
	batchRename: (paths: string[], template: string, startSeq: number) => typedError<BatchOpResult, string>(__TAURI_INVOKE("batch_rename", { paths, template, startSeq })),
	/**
	 *  批量导出（预设模式，T1 批次）：对 `paths`（顺序即序号顺序）逐张按命名模板渲染
	 *  输出基名，`convert::export_with_preset` 渲染（长边限制 + JPEG 质量 + 色调调整）。
	 *  占位符数据从内存 CaptureMeta 取（鸟种/日期/相机），序号从 `start_seq` 递增；
	 *  调整参数从 folder_db 读取（与 export_adjusted 同源）。同名输出已存在时自动追加
	 *  `_1/_2` 序号（照 export_adjusted 防覆盖语义，不覆盖原文件）。
	 * 
	 *  逐张 emit `export:progress`，完成 emit `export:done`（独立通道，避免与批量操作
	 *  进度互踩）。返回 `BatchOpResult` 形态汇总。
	 */
	exportCaptures: (paths: string[], outputDir: string, longEdge: number | null, quality: number, template: string, startSeq: number) => typedError<BatchOpResult, string>(__TAURI_INVOKE("export_captures", { paths, outputDir, longEdge, quality, template, startSeq })),
};

/* Types */
/**
 *  调整参数（参数化非破坏，ADR 0007）：per-capture，全零 = 无调整（短路现有渲染路径）。
 *  曝光/对比度/饱和度均为像素值变换（裁切已移除，见 ADR 0007 修订）。
 */
export type AdjustParams = {
	/**  曝光（EV，±2.0，步进 0.05；+1.0 EV = 曝光量翻倍） */
	exposure: number | null,
	/**  对比度（-100 ~ +100，0 中性） */
	contrast: number,
	/**  饱和度（-100 ~ +100，0 中性；-100 = 去饱和） */
	saturation: number,
};

export type AppConfig = {
	thumbnailSize?: number,
	favoriteDirs?: string[],
	lastDirectory?: string | null,
	recentDirectories?: string[],
	theme?: Theme,
	leftPanelWidth?: number,
	rightPanelVisible?: boolean,
	/**  右侧信息面板宽度（px）。旧配置无此字段时默认 200。 */
	rightPanelWidth?: number,
	fontFamily?: string,
	/**  批量识别线程数（1-4）。低配设备减小，高配设备加大。默认 4（8 核以上 CPU）。 */
	recognitionThreadCount?: number,
	/**  导出预设列表（T1 批次：命名模板/长边/质量组合）。旧配置无此字段时为空。 */
	exportPresets?: ExportPreset[],
	/**
	 *  扫描是否包含子目录（递归扫描全部子层）。默认 false = 单层扫描（保持现状）。
	 *  布尔字段无需钳制；改动后需重新扫描生效（scan 编排处按此值选单层/递归）。
	 */
	includeSubdirectories?: boolean,
	/**  网格堆叠模式（默认 ByTime = 同组照片堆叠；旧配置无此字段时回退默认）。 */
	stackMode?: StackMode,
};

/**  检测框：归一化坐标 [x1, y1, x2, y2]（0–1，相对图像宽高） */
export type BBox = {
	x1: number | null,
	y1: number | null,
	x2: number | null,
	y2: number | null,
};

/**  `batch:done` 事件负载：批量文件操作汇总 */
export type BatchDone = {
	success: number,
	failed: number,
};

/**  单个文件失败明细 */
export type BatchOpFailure = {
	path: string,
	error: string,
};

/**  干跑预览条目：path = 源主文件，targetPath = 目标位置（Delete 或无目标目录时为 null） */
export type BatchOpItem = {
	path: string,
	targetPath: string | null,
};

/**
 *  `batch_op_preview`/`batch_op_execute` 的选项：
 *  targetDir = Move/Copy 必填、Delete 忽略；syncSiblings + formats = 画面粒度同步同名兄弟
 */
export type BatchOpOptions = {
	/**  目标目录（Move/Copy 必填；Delete 忽略） */
	targetDir: string | null,
	/**  是否按同名扩展操作集（同步兄弟文件，画面粒度 ADR 0006） */
	syncSiblings: boolean,
	/**  同步扩展时参与兄弟匹配的格式白名单（空 = 不过滤/不扩展） */
	formats: ImageFormat[],
};

/**  `batch_op_preview` 返回：干跑结果（不碰文件） */
export type BatchOpPreview = {
	op: BatchOpType,
	count: number,
	items: BatchOpItem[],
	/**  同步扩展额外拉入的兄弟文件数 */
	siblingCount: number,
};

/**  `batch_op_execute` 返回 */
export type BatchOpResult = {
	success: number,
	failed: number,
	failures: BatchOpFailure[],
};

/**  批量文件操作类型（作用于当前筛选结果，ADR 0006） */
export type BatchOpType = 
/**  复制到目标目录 */
"Copy" | 
/**  删除（回收站） */
"Delete" | 
/**  移动到目标目录 */
"Move";

/**  `batch:progress` 事件负载：批量文件操作逐文件进度 */
export type BatchProgress = {
	done: number,
	total: number,
	currentPath: string,
};

/**  Top-N 候选（含未映射项：bird 为 None 表示该类别号未映射到名录） */
export type BirdCandidate = {
	/**  bird_model 原始类别号 */
	classIndex: number,
	/**  置信度（0–100） */
	confidence: number | null,
	/**  映射到的鸟种（未映射为 None） */
	bird: BirdMatch | null,
};

/**  鸟种匹配：分类器类别号经名录库映射到的具体鸟种 */
export type BirdMatch = {
	/**  名录库 animal_info 主键 */
	birdId: number,
	/**  中文名 */
	cnName: string,
	/**  学名（拉丁名） */
	latinName: string,
};

/**  `capture:enriched` 事件负载：EXIF 回填完成的 capture 索引（前端据此重排） */
export type CaptureEnriched = {
	indices: number[],
};

/**  发送到前端的拍摄摘要（轻量，不含完整 SourceFile） */
export type CaptureMeta = {
	index: number,
	baseName: string,
	primaryPath: string,
	primaryFormat: string,
	fileSize: number | null,
	dateTaken: string | null,
	extensions: string[],
	cameraMake: string | null,
	cameraModel: string | null,
	lens: string | null,
	exposureTime: string | null,
	fNumber: string | null,
	iso: number | null,
	focalLength: string | null,
	imageWidth: number | null,
	imageHeight: number | null,
	/**  GPS 纬度（十进制度；南纬为负；EXIF 无 GPS 为 None） */
	gpsLat: number | null,
	/**  GPS 经度（十进制度；西经为负；EXIF 无 GPS 为 None） */
	gpsLon: number | null,
	/**  对焦点（归一化坐标；相机未记录为 None） */
	focusPoint: FocusPoint | null,
	rating: Rating,
	colorLabel: ColorLabel,
	flag: Flag | null,
	keywords: string[],
	birdName: string | null,
	birdConfidence: number | null,
	recognitionStatus: RecognitionStatus | null,
	birdBbox: BBox | null,
	/**  鸟眼锐度分（与 Recognition::eye_sharpness 同源；无识别记录/无眼/评分失败为 None） */
	eyeSharpness: number | null,
};

/**  颜色标签 */
export type ColorLabel = "None" | "Red" | "Yellow" | "Green" | "Blue" | "Purple";

/**
 *  单鸟种识别命中率（get_correction_stats 返回项；与 engine global_db::CorrectionStat
 *  同构，核心层不含 serde，边界层在此补 serde + specta）。按 species_index 当前鸟种
 *  聚合：predicted = 被预测张数，corrected_away = 其中被人工改成别种的张数，
 *  accuracy = 1 - corrected_away/predicted。specta 对浮点导出 number|null（防御性
 *  NaN/Infinity 序列化），前端按 null 兜底。
 */
export type CorrectionStat = {
	birdName: string,
	predictedCount: number,
	correctedAwayCount: number,
	accuracy: number | null,
};

/**  `export:done` 事件负载：批量导出汇总（T1 批次） */
export type ExportDone = {
	success: number,
	failed: number,
};

/**  导出预设（T1 批次）：导出对话框的可复用组合（预设名 + 长边 + JPEG 质量 + 命名模板）。 */
export type ExportPreset = {
	/**  预设名（对话框下拉显示） */
	name?: string,
	/**  长边像素上限（None = 原尺寸；0 在钳制时归一为 None） */
	longEdge?: number | null,
	/**  JPEG 质量 1-100（保存/使用时钳制） */
	quality?: number,
	/**  命名模板（占位符语法见 engine template.rs：{name}/{species}/{date}/{seq}/{camera}） */
	template?: string,
};

/**
 *  `export:progress` 事件负载：批量导出逐张进度（T1 批次，与 batch:progress 同形态，
 *  独立通道避免与批量操作进度互相覆盖）
 */
export type ExportProgress = {
	done: number,
	total: number,
	currentPath: string,
};

/**  Pick/Reject 旗标 */
export type Flag = "Pick" | "Reject";

/**
 *  对焦点：归一化坐标（0–1，相对 orientation 修正后的显示方向），形状决定渲染形态。
 * 
 *  字段语义随形状变化：`Point` 时 (x, y) 为点位置、width/height 为 0；`Circle` 时
 *  (x, y) 为圆心、width = height = 直径；`Rectangle` 时 (x, y) 为左上角、width/height 为宽高。
 */
export type FocusPoint = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
	shape: FocusShape,
};

/**
 *  对焦点形状（EXIF SubjectArea 三形态 / RAW makernotes 映射）
 *  纯枚举不加 rename（对齐 Rating/ColorLabel 约定）：变体按原名序列化。
 */
export type FocusShape = 
/**  仅中心点（SubjectArea 1 值 / Fuji FocusPixel / Nikon·Panasonic AFPointSelected） */
"Point" | 
/**  圆形区域（SubjectArea 2 值：圆心 + 直径） */
"Circle" | 
/**  矩形区域（SubjectArea 3 值：左上角 + 宽高） */
"Rectangle";

/**
 *  `get_histogram` 返回：256 级 luma（BT.601 加权）+ RGB 三通道计数 + 剪切统计。
 *  各通道 Vec 恒为 256 个元素；totalPixels = 任一通道 bin 之和。
 */
export type HistogramPayload = {
	luma: number[],
	r: number[],
	g: number[],
	b: number[],
	/**  高光溢出像素数（luma >= 250） */
	clipHighCount: number,
	/**  死黑像素数（luma <= 5） */
	clipLowCount: number,
	/**  参与统计的总像素数 */
	totalPixels: number,
};

/**  图片格式枚举 */
export type ImageFormat = "Jpeg" | "Png" | "Tiff" | "Heif" | "WebP" | "Bmp" | "Gif" | { Raw: string } | "Other";

/**  导入候选（`scan_import_source` 返回 / `plan_import` 输入） */
export type ImportCandidate = {
	/**  源文件完整路径 */
	path: string,
	/**  拍摄日期 YYYY-MM-DD（EXIF 优先，回退 mtime） */
	date: string,
	/**  文件大小（字节，去重用） */
	size: number,
};

/**  `import:done` 事件负载：导入汇总 */
export type ImportDone = {
	imported: number,
	skipped: number,
	failed: number,
};

/**  可移动驱动器（`list_import_drives` 返回） */
export type ImportDrive = {
	/**  根路径（Windows 如 "E:\\"，Linux 为挂载点如 "/run/media/user/CANON"） */
	path: string,
	/**  卷标（读取失败/空卷标为 None） */
	label: string | null,
};

/**  导入计划组（目标目录 = destRoot/dateDir/） */
export type ImportGroup = {
	/**  日期目录名（YYYY-MM-DD，相对 destRoot） */
	dateDir: string,
	/**  组内源文件完整路径 */
	files: string[],
};

/**  导入执行模式 */
export type ImportMode = 
/**  复制（源保留） */
"Copy" | 
/**  移动（源删除；跨文件系统走 copy + delete 回退） */
"Move";

/**  导入计划（`plan_import` 返回 / `execute_import` 输入；干跑不碰文件） */
export type ImportPlan = {
	/**  按日期分组（YYYY-MM-DD） */
	groups: ImportGroup[],
	/**  跳过清单 */
	skipped: ImportSkipped[],
};

/**  `import:progress` 事件负载：逐文件进度 */
export type ImportProgress = {
	done: number,
	total: number,
	/**  当前处理的源文件路径 */
	current: string,
};

/**  `execute_import` 返回（与 import:done 同内容，供 invoke 调用方直接使用） */
export type ImportResult = {
	imported: number,
	skipped: number,
	failed: number,
};

/**  计划阶段被跳过的文件 */
export type ImportSkipped = {
	/**  源文件完整路径 */
	path: string,
	/**  跳过原因（目标已存在且大小相同 / 同名冲突等） */
	reason: string,
};

/**  评分 */
export type Rating = "None" | "One" | "Two" | "Three" | "Four" | "Five";

/**  一次识别的完整结果（不含路径；路径是持久化层的键） */
export type Recognition = {
	status: RecognitionStatus,
	/**  Top-1 鸟种匹配（mapping 失败 / 未检出时为 None） */
	bird: BirdMatch | null,
	/**  Top-1 原始类别号（诊断用） */
	classIndex: number | null,
	/**  Top-1 置信度（0–100） */
	confidence: number | null,
	/**  检测框（检测失败为 None） */
	bbox: BBox | null,
	/**  鸟眼锐度分（连续，仅保证单调性，阈值后置；无鸟/有鸟无眼/评分失败为 None） */
	eyeSharpness: number | null,
	/**  评分所用眼框（归一化坐标，相对全图；无锐度分为 None） */
	eyeBbox: BBox | null,
	/**  Top-5 候选（含 Top-1 自身除外的备选；分类失败为空） */
	candidates: BirdCandidate[],
	failureStage: RecognitionFailureStage,
	/**  ISO8601 时间戳 */
	recognizedAt: string,
};

/**  识别失败阶段 */
export type RecognitionFailureStage = "None" | "Detection" | "Classification" | "Mapping" | "Assets";

/**  识别状态（三态；无识别记录 = 未识别，不占枚举值） */
export type RecognitionStatus = 
/**  检测、分类、名录映射全部成功 */
"Confirmed" | 
/**  管线中途失败（分类异常 / 名录映射失败 / 源图不可用），需人工复核 */
"NeedsReview" | 
/**  检测阶段未发现鸟 */
"Unrecognized";

/**  `recognize:done` 事件负载：批量识别汇总（failed = 系统级失败张数，单张失败不中止整体） */
export type RecognizeDone = {
	total: number,
	confirmed: number,
	needsReview: number,
	unrecognized: number,
	failed: number,
};

/**  `recognize:progress` 事件负载：批量识别逐张进度 */
export type RecognizeProgress = {
	done: number,
	total: number,
	currentPath: string,
};

/**  `scan:done` 事件负载（directory 供前端同步当前目录状态，含启动自动恢复场景） */
export type ScanDone = {
	total: number,
	directory: string,
};

/**  `scan:progress` 事件负载 */
export type ScanProgress = {
	stage: ScanStage,
	done: number,
	total: number,
};

/**  扫描进度阶段：scan = 目录扫描 + DB 三表同步；exif = EXIF 增量提取；thumb = 缩略图预生成 */
export type ScanStage = "scan" | "exif" | "thumb";

/**  统计概览（get_species_stats 返回）：鸟种列表（张数降序）+ 覆盖文件夹数（汇总条用） */
export type SpeciesOverview = {
	stats: SpeciesStat[],
	folderCount: number,
};

/**  单张照片定位（get_species_photos 返回项；前端拼绝对路径 = folder + '/' + rel_path） */
export type SpeciesPhoto = {
	folder: string,
	relPath: string,
};

/**
 *  单鸟种聚合统计（get_species_stats 返回项；与 engine global_db::SpeciesStat 同构，
 *  核心层不含 serde，边界层在此补 serde + specta）
 */
export type SpeciesStat = {
	birdName: string,
	photoCount: number,
	firstDate: string | null,
	lastDate: string | null,
	avgSharpness: number | null,
};

/**
 *  网格堆叠模式：None = 不堆叠（每文件一项）；ByFileName = 同文件名（stem）合并
 *  （JPG/NEF 同画面，前端 stacks.ts 按 baseName 分组）；ByTime = 同组照片堆叠
 *  （拍摄时间差 ≤2s 的连拍合并，前端按 dateTaken 聚类）。默认 ByTime。
 */
export type StackMode = "None" | "ByFileName" | "ByTime";

/**
 *  侧栏目录树节点：name = 目录名，path = 完整路径，photoCount = 该目录**一层**
 *  直接包含的照片数（与 scanner 单层扫描同判据：viewable 扩展名，不含更深层）。
 *  更深层的子目录由前端在展开该节点时再调 list_subdirs 懒加载。
 */
export type SubdirInfo = {
	name: string,
	path: string,
	photoCount: number,
};

export type Theme = "Light" | "Dark";

/**  `thumb:ready` 事件负载：某张缩略图缓存已就绪（前端据此刷新对应 cell） */
export type ThumbReady = {
	path: string,
};

/**
 *  `undo_batch_operation` 返回：reverted = 成功撤销的文件数；
 *  skipped = (路径, 原因) 列表，原因区分「条件不满足跳过」与「执行失败」。
 */
export type UndoBatchResult = {
	reverted: number,
	skipped: ([string, string])[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}


// ============================================================================
// 手写补充类型（specta 生成物不含）：FilterCriteria/SortBy/SortDirection/
// RecognitionFilter 仅被前端筛选逻辑使用，Rust 侧无 command 引用它们，specta
// 不会导出；此处按 domain.rs 的 serde 输出（camelCase、外部标签枚举）补齐。
// 注意：重新运行 export-bindings 会覆盖此段，需手动保留。
// ============================================================================

/** 排序方式（domain.rs SortBy；EyeSharpness = 鸟眼锐度，T0 批次新增） */
export type SortBy = 'FileName' | 'DateTaken' | 'FileSize' | 'Rating' | 'Modified' | 'EyeSharpness'

/** 排序方向（domain.rs SortDirection） */
export type SortDirection = 'Ascending' | 'Descending'

/** 识别状态筛选（domain.rs RecognitionFilter；NotRecognized = 从未识别） */
export type RecognitionFilter = 'All' | 'Confirmed' | 'NeedsReview' | 'Unrecognized' | 'NotRecognized'

/** 筛选条件（domain.rs FilterCriteria，camelCase；sort 单独成字段见 filter store；
 *  iso/focal 区间为闭区间数值（mm/ISO），lens/keyword 空数组 = 不限） */
export type FilterCriteria = {
  formatFilter: ImageFormat | null
  birdNames: string[]
  dateFrom: string | null
  dateTo: string | null
  minRating: Rating | null
  colorLabel: ColorLabel | null
  flagFilter: Flag | null
  unflaggedFilter: boolean
  recognitionFilter: RecognitionFilter
  isoMin: number | null
  isoMax: number | null
  focalMin: number | null
  focalMax: number | null
  lensFilter: string[]
  keywordFilter: string[]
}
