[package]
name = "photo-tool-gpui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed", features = ["font-kit"] }
gpui-component = { git = "https://github.com/longbridge/gpui-component" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component" }
rfd = "0.17"
photo-tool-core = { path = "../photo-tool-core" }
image = "0.25"
smallvec = "1"
dirs = "6"
anyhow = "1.0"
